services:
  # thedatabase:
  #   image: postgres:14
  #   restart: always
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports: 
  #     - '5432:5432'
  web:
    platform: linux/x86_64
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/usr/src/app"
    ports:
      - "${APP_PORT}:3000"
    # depends_on:
    #   - thedatabase

  redis:
    image: redis:7.0
    environment:
      REDIS_PASSWORD: 'yourpassword'
    command: redis-server --requirepass yourpassword
    # volumes:
    #   - ./redis:/var/lib/redis/data
    ports:
      - '${REDIS_PORT}:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
